---
# ================================================
# ⚖️ markdownlint configuration — Legal Assistant Arbitrage v2.9.7 Docs Compliance
# ================================================

MD013:
  line_length: 160
  code_blocks: false
  tables: false
  headings: false
  strict: false

MD041: false   # allow frontmatter
MD003: false   # disable heading style enforcement
MD022: false   # no blank line requirement
MD010: false   # allow tabs
MD012: false   # multiple blanks ok
MD040: false   # no fenced code language enforcement
MD051: false   # link fragments not required
