---
# ===========================================
# 🧾 MarkdownLint Config — Legal Assistant Arbitrage v2
# ===========================================
default: true

# Разрешаем длинные строки (до 160 символов)
MD013:
  line_length: 160
  code_blocks: false
  tables: false
  headings: false

# Не требуем указания языка у код-блоков
MD040: false

# Разрешаем произвольную нумерацию списков
MD029: false

# Разрешаем отсутствие H1 на первой строке
MD041: false
