---
# ================================================
# ⚖️ yamllint configuration — Legal Assistant Arbitrage v2.9.7 LTS
# ================================================

extends: default

ignore: |
  node_modules/**
  venv/**
  artifacts/**
  logs/**
  .cache/**
  tmp/**
  __pycache__/**
  backup/**

rules:
  line-length:
    max: 160
    allow-non-breakable-words: true
    ignore: |
      .github/workflows/**
      docker-compose.yml
      docker-compose.prod.yml

  truthy: disable
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: enable
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  hyphens: enable
  quoted-strings:
    quote-type: double
    required: false
  key-duplicates: enable
  braces: enable
  brackets: enable
  colons: enable
