---
services:
  db:
    image: postgres:15
    restart: always
    container_name: legal-assistant-db
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    image: legal-assistant-arbitrage-v2_backend:latest
    container_name: legal-assistant-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: >
      sh -c "
        ./wait-for-db.sh &&
        alembic upgrade head &&
        uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8080:8000"
    volumes:
      - .:/code
      # ✅ Пробрасываем документацию внутрь контейнера
      - ./docs:/code/docs

volumes:
  pgdata:
