"""add updated_at to Decision

Revision ID: cf2677145b90
Revises: 2243736e0a51
Create Date: 2025-10-03 09:52:16.035668
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "cf2677145b90"
down_revision: Union[str, None] = "2243736e0a51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
