name: 🧪 KAD Integration & API Health CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  kad-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: legal_assistant_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d legal_assistant_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio respx ruff

      - name: 🧪 Run Kad integration tests
        run: |
          pytest -q backend/app/tests/test_kad_api.py -vv

      - name: 💓 Healthcheck API (local FastAPI run)
        run: |
          nohup uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          echo "⏳ Waiting for FastAPI to start..."
          sleep 10
          curl -s http://127.0.0.1:8000/api/health || (cat uvicorn.log && exit 1)
