name: Docker Build & Push

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    tags:
      - "v*.*.*"   # автосборка при релизе (например, v1.0.0)
  workflow_dispatch: # ручной запуск из Actions UI

jobs:
  docker:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')

    steps:
      # 1. Чекаутим репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Логинимся в Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Устанавливаем Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Определяем теги
      - name: Set Docker tags
        id: vars
        shell: bash
        run: |
          echo "sha_tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            version_tag="${GITHUB_REF#refs/tags/}"
            echo "version_tag=${version_tag}" >> "$GITHUB_OUTPUT"
          fi

      # 5. Собираем и пушим образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/legal-assistant-arbitrage-v2:latest
            ${{ secrets.DOCKER_USERNAME }}/legal-assistant-arbitrage-v2:${{ steps.vars.outputs.sha_tag }}
            ${{ secrets.DOCKER_USERNAME }}/legal-assistant-arbitrage-v2:${{ steps.vars.outputs.version_tag }}
